### ISSUE TITLE
The "working example" does not work

### ISSUE THREAD

**Issue by jononomo** [juliancwirko/meteor-pretty-diff#1]
I clicked on the link to see the "working example" but the site is down.

**Comment by juliancwirko** [comment]
oh, sorry. I forgot to change the link. The free meteor hosting is over now so *.meteor.com domains are unavailable. I've moved the service. The new link is: [pd.julian.io](http://pd.julian.io)

**Comment by jononomo** [comment]
Thanks.  Looks nice. Doesn't work if the file is named `foo.diff` but does if I change it to `foo.txt`.
